### ISSUE TITLE
feat: Additional objects in the chart

### ISSUE THREAD

**Issue by mhlgio** [homarr-labs/charts#116]
### Is your feature request related to a problem? Please describe.

I'm using 1Password with [Kubernetes Operator] for managing my secrets, I would like to have it passed in a single chart to homarr as well. I want to create a secret from 1Password item in a single values.yaml file, e.g.:

```
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: SECRET_NAME
spec:
  itemPath: "vaults/VAULT/items/ITEM"
```

### Describe the solution you'd like

Most likely it will be sufficient to add `additionalObjects` field and handle that. An example for `values.yaml` is here: https://github.com/goauthentik/helm/blob/main/charts/authentik/values.yaml#L1076-L1077.

Here is the corresponding template: https://github.com/goauthentik/helm/blob/main/charts/authentik/templates/additional-objects.yaml
