### ISSUE TITLE
bug: Doing helm uninstall does not remove Mysql's PVC

### ISSUE THREAD

**Issue by Heracles31** [homarr-labs/charts#121]
### Chart Version

latest

### Bug Description

After using helm to install both Homarr and the dedicated MySQL pod for it, a PVC is created for the database. When doing a helm uninstall, the PVC and the corresponding database remain in place. Should the install be performed again, the PVC and database will be re-used instead of starting from scratch with a clean setup.

### values.yaml

```yaml
relevant part of the values.yaml is :
mysql:
  internal: true
  existingSecret: db-secret
  username: homarr
  database: homarrdb
```

### Relevant log output

```shell

```
