### ISSUE TITLE
bug: Certificate not showing up in https://<homarr-fqdn>/manage/tools/certificates when configuring values.yaml with existingSecret

### ISSUE THREAD

**Issue by Jeswin-8801** [homarr-labs/charts#123]
### Chart Version

homarr-3.19.0

## `homarrTrustedCerts` of type `secret` when used with `existingSecret` does not have a volumeMount in the final deployment.yaml

In my `values.yaml`, I am referring to my custom root CA secret in `existingSecret`.

Output of:
```bash
helm template homarr oci://ghcr.io/homarr-labs/charts/homarr -n homarr -f values.yaml | less
````
Truncated:
```bash
.
.
.
          resources:
            {}
          volumeMounts:
            - name: homarr-database
              mountPath: /appdata/db
      volumes:
        - name: homarr-database
          persistentVolumeClaim:
           claimName: homarr-database
        - name: certificates
          secret:
            secretName: my-root-ca-secret
      hostAliases:
        - hostnames:
          - '*.home.local'
          ip: 192.168.0.63
```

There is no corresponding **volumeMount** for volume **certificates**. Therefore, no certificates show up in https://homarr.home.local/manage/tools/certificates

On referring https://github.com/homarr-labs/charts/blob/dev/charts/homarr/templates/homarr-secret.yaml, I find that the `existingSecret` does not get appended to `Values.persistence.homarrTrustedCerts.certificates` in the given configuration because the first line in the file checks for `not` of `existingSecret`

```yaml
{{- if and .Values.persistence.homarrTrustedCerts.enabled (not .Values.persistence.homarrTrustedCerts.existingSecret) (eq .Values.persistence.homarrTrustedCerts.type "secret") }}
```

BTW, just started out with Kubernetes. Am new to a lot of the concepts here. Pls do let me know if the above description is short on information or I am wrong about something.
Thanks.

### values.yaml

```yaml
persistence:
  homarrDatabase:
    enabled: true
    storageClassName: "longhorn"
    size: "1Gi"
  homarrTrustedCerts:
    enabled: true
    type: secret
    existingSecret: "my-root-ca-secret"
```

**Comment by oben01** [comment]
Hello @Jeswin-8801, thanks for reporting this issue. I confirm that's a valid bug.

When using persistence.homarrTrustedCerts.type: secret with existingSecret, the chart correctly defines the volume but does not create the corresponding volumeMount, so the certificates are not mounted into the container.

This currently only works when the secret is created by the chart itself. We'll update the chart to support mounting user-provided secrets and also consider allowing multiple secrets or configMaps to be mounted.

Thanks again for catching this!

**Comment by oben01** [comment]
@Jeswin-8801 I just fixed the issue in the latest version. here is the doc https://homarr-labs.github.io/charts/charts/homarr/#certificates please let me know if it fixed. Here is an example : 

```yaml
persistence:
  homarrTrustedCerts:
    enabled: true
    type: existingSecret
    existingSecretName: "existingSecretName"
    existingSecretKeys:
        - cert3.crt
        - cert4.crt
```
