### ISSUE TITLE
feat: add volumeClaim to PVC in order to match a specific PV

### ISSUE THREAD

**Issue by ixxeL2097** [homarr-labs/charts#62]
### Is your feature request related to a problem? Please describe.

In my setup, I value the option to set a `volumeName` in the `PersistentVolumeClaim` to be able to match a specific `PersistentVolume` that already exists for example. 

### Describe the solution you'd like

Add an optional key in `values.yaml` set to empty string by default : 
```yaml
    # -- homarr-database optional volumeClaimName
    volumeClaimName: ""
```
And then the added value in `PersistentVolumeClaim` : 
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $persistence.name }}
spec:
  accessModes:
    - {{ $persistence.accessMode }}
  storageClassName: "{{ $persistence.storageClassName }}"
  resources:
    requests:
      storage: {{ $persistence.size }}
  {{- if $persistence.volumeClaimName }}
  volumeName: "{{ $persistence.volumeClaimName }}"
  {{- end }}
```
Same logic can be replicated to all `PersistentVolumeClaim`
