### ISSUE TITLE
bug: error in the values.yaml fields for Ingress

### ISSUE THREAD

**Issue by Heracles31** [homarr-labs/charts#75]
### Chart Version

latest

### Bug Description

In the list of options in values.yaml, there is one that is described as :
```
ingress:
  className: "nginx"
```
That does not work and the proper name for the option is ingressClassName
```
ingress:
  ingressClassName: "nginx"
```

### values.yaml

```yaml

```

### Relevant log output

```shell

```

**Comment by oben01** [comment]
@Heracles31 Which version of the chart are u using ? 
I just tried those values : 
```yaml
# Ingress configuration
ingress:
  # -- Enable ingress
  enabled: true
  # -- Ingress class name
  ingressClassName: "nginx"
  # -- Ingress annotations
  annotations: {}
    # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  # -- Ingress hosts configuration
  hosts:
    - host: chart-example.local
      paths:
        - path: /
  # -- Ingress TLS configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
```

Am getting as an output 

```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: release-name-homarr
  labels:
    helm.sh/chart: homarr-3.2.0
    app.kubernetes.io/name: homarr
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "v1.11.0"
    app.kubernetes.io/managed-by: Helm
spec:
  ingressClassName: nginx
  rules:
    - host: "chart-example.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: release-name-homarr
                port:
                  number: 7575

```

I don't see no problem with it. let me know if i miss something
